"""admin users and sessions

Revision ID: 4a093aff9ce7
Revises: cb5a089b8ccc
Create Date: 2026-07-22 02:25:45.807859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4a093aff9ce7'
down_revision: Union[str, None] = 'cb5a089b8ccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_user_login'), 'admin_user', ['login'], unique=True)
    op.create_table('admin_session',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['admin_user.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_admin_session_expires_at'), 'admin_session', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_session_expires_at'), table_name='admin_session')
    op.drop_table('admin_session')
    op.drop_index(op.f('ix_admin_user_login'), table_name='admin_user')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
