"""service call comment

Revision ID: 7997f34d84b2
Revises: bfcaf122381b
Create Date: 2026-07-22 12:07:16.666605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7997f34d84b2'
down_revision: Union[str, None] = 'bfcaf122381b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_call', sa.Column('comment', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_call', 'comment')
    # ### end Alembic commands ###
