"""menu editing: sort order and archive flags

Revision ID: bfcaf122381b
Revises: 4a093aff9ce7
Create Date: 2026-07-22 02:32:53.604951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bfcaf122381b'
down_revision: Union[str, None] = '4a093aff9ce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default нужен, чтобы колонки легли на уже существующие строки;
    # после заливки значения снимаем — дальше их проставляет приложение
    op.add_column('category', sa.Column('is_archived', sa.Boolean(), nullable=False,
                                        server_default=sa.false()))
    op.add_column('dish', sa.Column('is_archived', sa.Boolean(), nullable=False,
                                    server_default=sa.false()))
    op.add_column('dish', sa.Column('sort_order', sa.Integer(), nullable=False,
                                    server_default='0'))
    op.alter_column('category', 'is_archived', server_default=None)
    op.alter_column('dish', 'is_archived', server_default=None)
    op.alter_column('dish', 'sort_order', server_default=None)

    # порядок блюд внутри категории: сохраняем нынешний вид меню (по id)
    op.execute('''
        UPDATE dish SET sort_order = numbered.position
        FROM (
            SELECT id, row_number() OVER (PARTITION BY category_id ORDER BY id) AS position
            FROM dish
        ) AS numbered
        WHERE dish.id = numbered.id
    ''')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dish', 'sort_order')
    op.drop_column('dish', 'is_archived')
    op.drop_column('category', 'is_archived')
    # ### end Alembic commands ###
