"""service calls, order comments, dish descriptions

Revision ID: cb5a089b8ccc
Revises: 02242f6b581d
Create Date: 2026-07-22 01:39:37.597542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cb5a089b8ccc'
down_revision: Union[str, None] = '02242f6b581d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_call',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actor_telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('tg_message_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['point_id'], ['point.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_call_point_id'), 'service_call', ['point_id'], unique=False)
    op.add_column('dish', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('orders', sa.Column('comment', sa.String(length=300), nullable=True))
    op.add_column('orders', sa.Column('reminded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'reminded_at')
    op.drop_column('orders', 'comment')
    op.drop_column('dish', 'description')
    op.drop_index(op.f('ix_service_call_point_id'), table_name='service_call')
    op.drop_table('service_call')
    # ### end Alembic commands ###
